### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/actividad-1-infografia-Julissamigdalia#2]
[Infografia (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Julissamigdalia/files/12491753/Infografia.1.pdf)

**Comment by YaelStO** [comment]
Buen trabajo 18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
